# Generated by Django 3.0.14 on 2022-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='soluong',
            field=models.IntegerField(default=0),
        ),
    ]
