# Generated by Django 3.0.14 on 2022-05-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220516_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='producttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ProductType'),
        ),
    ]
